services:
  app:
    build:
      context: ../..
      dockerfile: setup/dev/app/Dockerfile
    env_file:
      - ../../.env
    ports:
      - "8080:8080" 
    container_name: "docker_restaurant_app"
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    networks:
      - backend
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:16
    env_file:
      - ../../.env
    container_name: "docker_restaurant_postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "docker_restaurant_rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: unless-stopped
  
  webserver:
    image: nginx:alpine
    container_name: "docker_restaurant_webserver"
    ports:
      - "80:80" 
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - backend
    depends_on:
      - app
    restart: unless-stopped

volumes:
  logs_data:
  postgres_data:

networks:
  backend:
    name: backend
    driver: bridge