name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        id: go

      - name: Test application
        run: go test -v

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Publish to GCR
        run: |
          gcloud builds submit --tag gcr.io/blog-357212/exemplo-go .

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: exemplo-go
          image: gcr.io/blog-357212/exemplo-go:latest
          region: europe-west1
          flags: "--port=1323" # Flag para especificar a porta da aplicação